### ISSUE TITLE
Need to escape double quotes for flamegraph

### ISSUE THREAD

**Issue by 0x62ash** [timbunce/devel-nytprof#92] opened 2016-02-22 11:06 UTC
Profiling for Time::Moment produces flamegraph with invalid svg in onmouseover token.

```js
<g class="func_g" onmouseover="s('Time::Moment::("" (3,305 microseconds, 0.03%)')" onmouseout="c()">
<title>Time::Moment::("" (3,305 microseconds, 0.03%)</title><a xlink:href="Time-Moment-pm-209-line.html#Time__Moment_____" target="_top"><rect x="1107.5" y="321" width="0.3" height="15.0" fill="rgb(206,55,48)" rx="2" ry="2" />
</a>
</g>
```

**Comment by timbunce** [comment] 2016-03-19 23:16
Thanks for the report. Closing as duplicate of #39 (which is old and needs some love).

**Closed by timbunce** 2016-03-19 23:16 UTC
