### ISSUE TITLE
Tests failing for Devel-NYTProf 6.03 under strawberry perl 5.22.1 x64

### ISSUE THREAD

**Issue by tomk3003** [timbunce/devel-nytprof#94] opened 2016-05-10 13:39 UTC
Hi,
here the test results for Devel-NYTProf 6.03 under strawberry perl 5.22.1 x64
Thomas

[test_out.txt](https://github.com/timbunce/devel-nytprof/files/257266/test_out.txt)

**Comment by tomk3003** [comment] 2016-05-11 14:36
Sorry typo make that strawberry-perl 5.22.2.1

**Comment by shawnlaffan** [comment] 2017-01-14 07:30
I get the same basic errors under Strawberry Perl 5.24.0.1 x64

These errors also look to be the same as those in #76

**Comment by shawnlaffan** [comment] 2018-03-27 01:30
The issue could be related to something in the Strawberry Perl portable edition.  

I can reproduce the test failures when using Strawberry Perl 5.26.1 portable edition (installed via Berrybrew).  

However, when I use Strawberry Perl via the MSI installer (installed into C:\Strawberry) then all tests pass.

I don't know why there are differences, but the errors are consistent and reproducible.

**Comment by timbunce** [comment] 2018-06-04 12:40
Closed by #123, I hope.

**Comment by jkeenan** [comment] 2021-04-06 21:07
@shawnlaffan , @tomk3003:  https://github.com/timbunce/devel-nytprof/pull/123 was applied in 2018 to address the concerns you raised in this ticket.  Can you confirm whether the problem was resolved?  (Note: Devel-NYTProf-6.07 was released this morning.)

Thank you very much.
Jim Keenan

**Comment by shawnlaffan** [comment] 2021-04-06 21:49
I've had no issues testing Devel::NYTProf since #123 was merged.  This includes 6.07 which I just installed under Strawberry Perl 5.28 portable.

The changes to test expectations in #123 are pretty fragile, but can be updated again if a similar issue appears and a more general solution is not obvious.

**Comment by jkeenan** [comment] 2021-04-24 15:23
> I've had no issues testing Devel::NYTProf since #123 was merged. This includes 6.07 which I just installed under Strawberry Perl 5.28 portable.
> 
> The changes to test expectations in #123 are pretty fragile, but can be updated again if a similar issue appears and a more general solution is not obvious.

Thanks for your response.  I'm closing this issue.  Please open a new one if you experience problems going forward.

**Closed by jkeenan** 2021-04-24 15:23 UTC
Labels: Windows, closable?
